import React from 'react'
import {
  TechLogosContainer,
  Icon,
  ImageContainer
} from './TechLogoContainer.styles'

export const TechLogoContainer = () => {
  return (
    <TechLogosContainer>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722823/Portfolio/Tech-logos/react.svg'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722824/Portfolio/Tech-logos/sassLogo.svg'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722823/Portfolio/Tech-logos/mongoDB.png'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722823/Portfolio/Tech-logos/htmlcss.png'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722824/Portfolio/Tech-logos/redux.png'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722823/Portfolio/Tech-logos/netlify.png'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722823/Portfolio/Tech-logos/nodejs-new-pantone-black.png'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722823/Portfolio/Tech-logos/javascript.png'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722823/Portfolio/Tech-logos/firebase.png'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
      <Icon>
        <ImageContainer>
          <img
            src='https://res.cloudinary.com/dmtn5fbdu/image/upload/v1574722823/Portfolio/Tech-logos/express.png'
            alt='logo'
          />
        </ImageContainer>
      </Icon>
    </TechLogosContainer>
  )
}
